# Jekyll configuration for GitHub Pages
title: Poll Everywhere Notifier
description: A Chrome extension to notify students when new Poll Everywhere questions are posted
theme: jekyll-theme-primer

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Site settings
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
